### ISSUE TITLE
"ABORTED" immidiately after launch

### ISSUE THREAD

**Issue by hit0wnzzz** [d99kris/nchat#208] opened 2024-03-19 16:44 UTC
Immidiately after launch, i get "ABORTED" message.

Sometimes removing the account and setting up again will have nchat working for a couple of days.

WSL Ubuntu 22.04.03 - Windows 10

attached log:
[log.txt](https://github.com/d99kris/nchat/files/14653705/log.txt)

**Comment by hit0wnzzz** [comment] 2024-03-19 16:44
![image](https://github.com/d99kris/nchat/assets/13006851/40f0ba8b-351b-4129-babb-3e387903bf19)

**Comment by d99kris** [comment] 2024-03-20 11:38
Hi @hit0wnzzz - thanks for the detailed bug report! It is possible this issue has been fixed in newer versions of nchat. According to the log you're using v4.13 (latest stable release), while latest master is v4.41. The next stable release is targetted this weekend. So if you prefer to use stable releases, you could wait until then, update and see if the problem is fixed.

If you don't mind doing some debugging, you could help to obtain the backtrace of the crash by following these steps:

```
1. Enable core dumps
ulimit -c unlimited

2. Run nchat
nchat

3. Upon encountering crash, the following should be output on the terminal:
Aborted (core dumped)

4. Reset terminal and check core dump location
reset
cat /proc/sys/kernel/core_pattern

6. Assuming the output is /mnt/wslg/dumps/core.%e, then do:
gdb $(which nchat) /mnt/wslg/dumps/core.nchat -ex backtrace -ex quit

7. Copy the output of above command and paste in a comment here.
```

Note: ulimit is per shell session, so it may be safest to call it every time before starting nchat, in case you rebooted or switched terminal window. In newer versions of nchat (from v4.25) one can enable core dumps using an app.conf setting, without the need to call ulimit.

**Comment by d99kris** [comment] 2024-03-23 13:32
Hi - the quarterly stable release of nchat is available now. Please try it out and let me know if the crash is fixed. Thanks!

**Comment by d99kris** [comment] 2024-04-24 10:32
Hi again - I cannot troubleshoot this further without more information, so I will proceed to close this issue. Feel free to re-open it if you're still facing the issue, and please help provide additional details mentioned in my earlier comment.

**Closed by d99kris** 2024-04-24 10:32 UTC
Labels: bug
