### ISSUE TITLE
nchat crashes on startup

### ISSUE THREAD

**Issue by alohawolf** [d99kris/nchat#4] opened 2019-09-11 00:43 UTC
nchat crashes on startup

last message in log is 

std::out_of_range'
  what():  map::at

I'm happy to send full log to you, but not post on GitHub @alohwolf is my username

**Comment by alohawolf** [comment] 2019-09-11 00:59
Note this was on ubuntu 18.04 where the issue occurred - there is another related crash were cycling too radpidly thru chats will cause the application to crash

**Comment by alohawolf** [comment] 2019-09-11 01:29
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: map::at:  key not found

Same crash happens on macOS when cycling thru contacts too rapidly.

**Comment by d99kris** [comment] 2019-09-22 13:31
Hi @alohawolf - thanks for reporting the crashes. I have not been able to reproduce neither the startup crash nor the cycling through contacts crash (I tested on macOS 10.14.6 and Ubuntu 18.04 LTS).

Previous nchat logging was not very extensive, but in https://github.com/d99kris/nchat/commit/95711155074f67ed4c79e922c312357695929262 I've implemented some improved logging. Could you help update to latest code base and reproduce the problem again, and then share your `~/.nchat/main.log` with me?

That particular log file should not contain any sensitive information, and should be safe to upload to this issue report. But if you prefer, feel free to share it via Telegram for example. 

Thanks!

**Comment by alohawolf** [comment] 2019-09-22 15:09
@d99kris here is the crash dump from this morning.

I built it on both MacOS and Ubuntu 18.04 for testing, and it crashed on both.

[main.log](https://github.com/d99kris/nchat/files/3639852/main.log)
[macos.main.log](https://github.com/d99kris/nchat/files/3639873/macos.main.log)

**Comment by d99kris** [comment] 2019-09-23 10:55
Thanks for the logs @alohawolf - I still couldn't reproduce the crash, but I found a possible place where the program can crash, based on the logs. I just pushed a fix for it. 

Please let me know if it fixes the problem. 
Thanks!

**Comment by alohawolf** [comment] 2019-09-23 20:17
This resolved the crash issue for me.

**Comment by d99kris** [comment] 2019-09-24 11:16
Great, thanks for confirming! Will close the issue.

**Closed by d99kris** 2019-09-24 11:16 UTC
